run:
  timeout: 3m
  go: "1.24"
  skip-dirs:
    - vendor

linters:
  disable-all: true
  enable:
    - govet
    - gofmt
    - goimports
    - ineffassign
    - errcheck
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/vaughanb/typeconv

issues:
  exclude-use-default: false


