name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
          check-latest: true

      - name: Go version
        run: go version | cat

      - name: Dependencies
        run: make deps

      - name: Tidy
        run: make tidy

      - name: Format
        run: make fmt

      - name: Vet
        run: make vet

      - name: Test
        run: make test

      - name: Coverage
        run: make cover

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.0

      - name: Lint
        run: make lint

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            coverage.out
            coverage.html
          if-no-files-found: ignore


